---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

before_script:
    - ember sauce:connect

after_script:
    - ember sauce:disconnect

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test

env:
  global:
    - SAUCE_USERNAME=jquerysf-demo-ebryn
    - SAUCE_ACCESS_KEY=e66d36ff-637f-4b0a-9523-0d8b826b75f2